spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/products_database_opt?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/web_market_db?createDatabaseIfNotExist=true
#    url: jdbc:mysql://localhost:3306/dump_web_market_db?createDatabaseIfNotExist=true
    username: root
#    password: 6830
    password: 312808895
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: validate #Невмешательство в структуру БД, только чтение
#      ddl-auto: create #Полная очистка и создание новой БД при старте Spring
#      ddl-auto: create-drop #Полная очистка и создание новой БД при старте Spring + очистка после завершения Spring
      ddl-auto: update #Обновление структуры БД

  jackson:
    serialization:
      indent-output: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8083
  servlet:
    context-path: /market-auth

jwt:
  secret: skljghiklk*/*h*mdbbKJH0832dfdlgb645dsrfg4234HGU5+6/56SEDKJjhb3hg
  expire-time: PT5M

