spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/products_database_opt?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/web_market_db?createDatabaseIfNotExist=true
#    url: jdbc:mysql://localhost:3306/dump_web_market_db?createDatabaseIfNotExist=true
    username: root
    password: 6830 # работа
    #    password: 312808895 # дом
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: validate #Невмешательство в структуру БД, только чтение
#      ddl-auto: create #Полная очистка и создание новой БД при старте Spring
#      ddl-auto: create-drop #Полная очистка и создание новой БД при старте Spring + очистка после завершения Spring
      ddl-auto: update #Обновление структуры БД

  jackson:
    serialization:
      indent-output: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081
  servlet:
    context-path: /market-order

integrations:
  product-service:
    url-products-service: "http://localhost:8084/market-products"
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

  auth-service:
    url-auth-service: "http://localhost:8083/market-auth"
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000


